In [33]:
import numpy as np
array =np.array([[1,2,3],[2,3,4]])
print(array)
print('number of dim:', array.ndim)
print('shape', array.shape)
print('size', array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape (2, 3)
size 6


In [34]:
#Python numpy Array

a=np.array([2,23,4],dtype=np.int32)
print(a.dtype)
a=np.array([2,23,4],dtype=np.float32)
print(a.dtype)
a=np.zeros((3,4), dtype=np.int16)
print(a)
a=np.empty((3,4))
print(a)
a=np.arange(10,20,2)
print(a)
a=np.arange(12).reshape((3,4))
print(a)
a=np.linspace(1,10,6).reshape((2,3))
print(a)

int32
float32
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]


In [35]:
#Python numpy Vectorized Computation

a =np.array([10,20,30,40])
b =np.arange(4)

print(a,b)

c = a+b
print(c)

c = a**b
print(c)

c = 10*np.sin(a)
print(c)

print(b<3)
print(b==3)

a=np.array([[1,1],
           [0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)

c=a*b
c_dot=np.dot(a,b)
print(c)
print(c_dot)
c_dot2=a.dot(b)
print(c_dot2)

a=np.random.random((2,4))
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))


[10 20 30 40] [0 1 2 3]
[10 21 32 43]
[    1    20   900 64000]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True  True False]
[False False False  True]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]
[[ 0.20989153  0.64361363  0.56837301  0.58185991]
 [ 0.19858458  0.38041605  0.92604407  0.21583291]]
3.72461569594
[ 0.40847611  1.02402968  1.49441708  0.79769282]
[ 2.00373809  1.72087761]
0.198584584216
[ 0.19858458  0.38041605  0.56837301  0.21583291]
[ 0.20989153  0.19858458]
0.92604406887
[ 0.20989153  0.64361363  0.92604407  0.58185991]
[ 0.64361363  0.92604407]


In [36]:
A=np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.sort(A))

# Get the transpose
print(np.transpose(A))
print((A.T))
print((A.T).dot(A))

# Find out the index of min, max
print(np.argmin(A))
print(np.argmax(A))

print(np.median(A))
print(np.mean(A))
print(np.mean(A,axis=0))
print(np.mean(A,axis=1))
print(A.mean())

print(np.average(A))
print(np.cumsum(A))
print(np.diff(A))

# Find the nonezero index of the array
print(np.nonzero(A))

# Clip 
print(np.clip(A,5,9))



[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
11
0
8.5
8.5
[ 10.   9.   8.   7.]
[ 12.5   8.5   4.5]
8.5
8.5
[ 14  27  39  50  60  69  77  84  90  95  99 102]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [37]:
#numpy indexing
A=np.arange(3,15).reshape(3,4)
print(A)
print(A[2][1])
print(A[2,:])
print(A[:,1])
print(A[1,1:3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
12
[11 12 13 14]
[ 4  8 12]
[8 9]


In [38]:
# for loop and flatten
print(A)
print(A.T)
print(A.flatten())

for row in A:
    print(row)
    
for column in A.T:
    print(column)
    
for item in A.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [39]:
# vstack, hstack
A = np.array([1,1,1])
B = np.array([2,2,2])

C = np.vstack((A,B)) #vertical Stack
D = np.hstack((A,B)) #horizontal Stack
print(C)
print(D)
print(A.shape, C.shape)
print(A.shape, D.shape)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
(3,) (2, 3)
(3,) (6,)


In [40]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

C = np.vstack((A,B)) #vertical Stack
D = np.hstack((A,B)) #horizontal Stack
print(C)
print(D)
print(A.shape, C.shape)
print(A.shape, D.shape)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
(3, 1) (6, 1)
(3, 1) (3, 2)


In [41]:
# Concatenate
C=np.concatenate((A,B,B,A),axis=0)
print(C)
D=np.concatenate((A,B,B,A),axis=1)
print(D)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [42]:
# Split
A = np.arange(12).reshape((3,4))
print(A)
print(np.split(A,2,axis=1))
print(np.split(A,3,axis=0))
print(np.array_split(A,3,axis=1))
print(np.vsplit(A,3))
print(np.hsplit(A,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [43]:
# numpy copy & deep copy
a=np.arange(4)
print(a)
b=a
c=a
d=b

a[0]=11
print(a)
print(b is a)
print(d is a)

[0 1 2 3]
[11  1  2  3]
True
True


In [44]:
#deep copy
b=a.copy()
a[3]=44
print(a)
print(b)

[11  1  2 44]
[11  1  2  3]
